baseurl: "/LokHopVerk"
<<<<<<< HEAD
<<<<<<< HEAD
url: "https://kleina13.github.io/lokhopverk"
=======
url: "https://kleina13.github.io/LokHopVerk"
>>>>>>> c698f6376cbd0982ff2be885ed8b1096f1fe4278
=======
url: "https://kleina13.github.io/LokHopVerk"
=======
url: "https://kleina13.github.io/lokhopverk"
>>>>>>> 222b622f1af0fe3d1b8945118df4d08ea16ff939
>>>>>>> 5c48e65f4f2d27cd955f3cd4fa0b780e0d8f46d7
